unicef/hope

- backend/hct_mis_api/apps/payment/templates/payment/payment_plan_summary_pdf_template.html
[AB#188195](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/188195)
> 1188195_Payment_Plan_summary_file_fix

- backend/hct_mis_api/apps/utils/mailjet.py
- backend/hct_mis_api/settings.py
[AB#191896](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/191896)
> [191896] Mailjet integration

- backend/hct_mis_api/apps/payment/notifications.py
- backend/hct_mis_api/apps/payment/tests/test_action_payment_plan_mutation.py
- backend/hct_mis_api/apps/payment/tests/test_payment_notification.py
[AB#192286](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/192286)
> [192286] Implement mailjet for payment plan notification

- frontend/src/containers/pages/paymentmodule/SetUpFollowUpFspPage.tsx
- frontend/src/containers/routers/PaymentModuleRoutes.tsx
[AB#192594](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/192594): Cannot open page to set up FSP in a follow up payment plan
> HOTFIX // Set Up FSP FollowUp PaymentPlan

- backend/hct_mis_api/apps/payment/celery_tasks.py
- backend/hct_mis_api/apps/payment/notifications.py
- backend/hct_mis_api/apps/payment/services/payment_plan_services.py
- backend/hct_mis_api/apps/payment/templates/payment/payment_plan_action.html
- backend/hct_mis_api/apps/payment/templates/payment/payment_plan_action.txt
- backend/hct_mis_api/apps/payment/tests/test_action_payment_plan_mutation.py
- backend/hct_mis_api/apps/payment/tests/test_payment_notification.py
[AB#187069](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/187069)
> [187069] Payment notification - pass user and date

- backend/hct_mis_api/libs/power_query/defaults.py
[AB#192816](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/192816)
> fix upgrade command

- backend/hct_mis_api/apps/program/utils.py
[AB#192656](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/192656)
> [HOTFIX] [192656] RDI enrollment - compress error message

- backend/hct_mis_api/api/endpoints/rdi/base.py
- backend/hct_mis_api/api/endpoints/rdi/mixin.py
- backend/hct_mis_api/api/endpoints/rdi/program.py
- backend/hct_mis_api/api/endpoints/rdi/upload.py
- backend/hct_mis_api/api/tests/base.py
- backend/hct_mis_api/api/tests/test_program.py
- backend/hct_mis_api/api/tests/test_rdi.py
- backend/hct_mis_api/api/tests/test_soft.py
- backend/hct_mis_api/apps/registration_data/admin.py
- backend/hct_mis_api/apps/registration_datahub/admin.py
- backend/hct_mis_api/apps/registration_datahub/models.py
[AB#192695](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/192695)
> [HOTFIX][192695] Admin fixes

- backend/hct_mis_api/apps/household/models.py
[AB#193050](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/193050)
> [HOTFIX][193050] Fix wrong information about sanction list last check

- backend/hct_mis_api/apps/core/admin.py
- backend/hct_mis_api/apps/core/forms.py
- backend/hct_mis_api/apps/core/tests/test_admin.py
[AB#193571](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/193571)
> [193571] Admin Panel DCT settings enhancements

- backend/hct_mis_api/apps/grievance/tasks/deduplicate_and_check_sanctions.py
- backend/hct_mis_api/apps/registration_datahub/tasks/rdi_merge.py
- backend/hct_mis_api/apps/sanction_list/tests/test_check_against_sanction_list_pre_merge.py
[AB#193221](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/193221)
> [193221] Sanction list screening feature check

- backend/hct_mis_api/apps/payment/tests/test_payment_notification.py
- backend/hct_mis_api/apps/utils/mailjet.py
- backend/hct_mis_api/settings.py
- backend/hct_mis_api/settings_test.py
[AB#191896](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/191896)
> [191896] Mailjet - catch all email

- backend/hct_mis_api/api/endpoints/rdi/delegate_people.py
- backend/hct_mis_api/api/endpoints/rdi/push_people.py
[AB#193048](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/193048)
> [193048] Add swagger

- backend/hct_mis_api/apps/grievance/services/data_change/individual_dalete_service.py
- backend/hct_mis_api/apps/grievance/services/data_change/utils.py
- backend/hct_mis_api/apps/grievance/services/needs_adjudication_ticket_services.py
- backend/hct_mis_api/apps/grievance/services/reassign_roles_services.py
[AB#193983](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/193983)
> [HOTFIX] [193983] Can close ticket with individual withrawal without household

- backend/hct_mis_api/middlewares/sentry.py
[AB#194205](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/194205): RDI API does not set proper Sentry tags
> Add sentry tag BA for api calls

- backend/hct_mis_api/apps/payment/admin.py
- backend/hct_mis_api/apps/payment/models.py
[AB#193041](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/193041)
> [193041] Admin enhancement - payment

- frontend/src/components/payments/VerifyManual.tsx
- frontend/src/containers/pages/payments/VerificationPaymentDetailsPage.tsx
- frontend/src/containers/pages/payments/VerificationPaymentRecordDetailsPage.tsx
[AB#194006](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/194006)
> [194006] Fix fill `receivedAmount` on edit

- backend/hct_mis_api/apps/program/admin.py
[AB#193040](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/193040)
> [193040] Admin enhancement - program

- frontend/src/apollo/client.ts
- frontend/src/containers/pages/accountability/communication/CreateCommunicationPage.tsx
- frontend/src/containers/pages/accountability/surveys/CreateSurveyPage.tsx
[AB#194046](https://unicef.visualstudio.com/ICTD-HCT-MIS/_boards/board/t/HOPE%20Team/Stories/?workitem=194046)
> [194046]-error message when triggering rapid pro

- frontend/src/components/paymentmodule/PaymentPlanDetails/PaymentPlanDetailsHeader/SplitIntoPaymentLists.tsx
[AB#194076](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/194076)
> payment plan split validation message fix

- backend/hct_mis_api/apps/account/models.py
- backend/hct_mis_api/apps/account/tests/test_user_roles.py
[AB#192988](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/192988)
> [192988] Fix partner permissions

- .github/workflows/ci.yml
[AB#177836](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/177836)
CodeCov is available [here](https://app.codecov.io/gh/unicef/hct-mis)
> [177836] Add codecov

- backend/hct_mis_api/apps/account/models.py
- backend/hct_mis_api/apps/payment/xlsx/xlsx_payment_plan_import_service.py
[AB#189308](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/189308)
> [189308] Optimize for import_payment_plan_payment_list_from_xlsx

- frontend/src/App.tsx
[AB#195876](https://unicef.visualstudio.com/ICTD-HCT-MIS/_boards/board/t/HOPE%20Team/Stories/?workitem=195876)
> redirect to programs list if url === /:businessArea

- backend/hct_mis_api/api/endpoints/rdi/base.py
[AB#197340](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/197340)
> [197340] RDI API: counters missing values

- backend/hct_mis_api/apps/registration_datahub/tests/test_xlsx_upload_validators_methods.py
- backend/hct_mis_api/apps/registration_datahub/validators.py
[AB#197924](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/197924)
> 197924 change label

- backend/hct_mis_api/apps/payment/schema.py
- backend/hct_mis_api/apps/payment/tests/test_fsp_in_payment_plan.py
[AB#192437](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/192437)
> [192437] Limit FSP visibility to specific BAs

- frontend/src/apollo/client.ts
[AB#199275](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/199275)
> [199275] Wrong redirect url

- frontend/src/components/grievances/LookUps/LookUpLinkedTickets/LookUpLinkedTicketsModal.tsx
- frontend/src/components/targeting/CreateTPMenu.tsx
- frontend/src/components/targeting/EditTargetPopulation/EditTargetPopulationHeader.tsx
- frontend/src/components/targeting/TargetingCriteria/TargetingCriteria.tsx
- frontend/src/containers/pages/targeting/TargetPopulationsPage.tsx
[AB#194159](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/194159)
> [194159] Grievance - Not possible to add linked ticket

- backend/hct_mis_api/apps/reporting/services/generate_report_service.py
[AB#192280](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/192280): Reporting - 'Payment plan' report is not generating results for Ukraine
> [STG] Reporting: Fix Payment plan filtering

- backend/hct_mis_api/api/endpoints/rdi/push_people.py
- backend/hct_mis_api/api/tests/test_push_people.py
[AB#199674](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/199674)
> [199674] Fix validate phone number

- frontend/fixtures/population/fakeApolloAllHouseholdsForPopulationTable.ts
- frontend/src/components/core/DocumentSearchField.test.tsx
- frontend/src/components/core/DocumentSearchField.tsx
- frontend/src/components/core/SearchTextField.tsx
- frontend/src/components/core/__snapshots__/DocumentSearchField.test.tsx.snap
- frontend/src/components/grievances/GrievancesTable/GrievancesFilters.tsx
- frontend/src/components/population/HouseholdFilter.tsx
- frontend/src/components/population/IndividualsFilter.tsx
- frontend/src/containers/tables/Communication/LookUpHouseholdTableCommunication/LookUpHouseholdTableCommunication.tsx
[AB#177497](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/177497)
According to a request from https://github.com/unicef/hct-mis/pull/3795#issuecomment-2078984492
> [177497] Search enhancement

- frontend/src/components/programs/ProgramDetails/ProgramDetails.tsx
[AB#199793](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/199793)
> [199793] Missing ADMIN AREA 3 and ADMIN AREA 4 in Programme Details

- backend/hct_mis_api/api/endpoints/rdi/push_people.py
- backend/hct_mis_api/api/endpoints/rdi/upload_people.py
- backend/hct_mis_api/api/tests/test_push_people.py
- backend/hct_mis_api/api/tests/test_upload_people.py
- backend/hct_mis_api/apps/registration_datahub/models.py
[AB#199779](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/199779)
> [199779] Convert phone number None => empty string

- frontend/src/components/targeting/TargetPopulationCore.tsx
- frontend/src/containers/forms/ProgramForm.tsx
- frontend/src/shared/autocompletes/TargetPopulationAutocomplete.tsx
[AB#185495](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/185495)
[AB#198144](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/198144)
> [185495,198144]-results for people tp/fix target population autocomplete

- backend/hct_mis_api/apps/core/fixtures/businessareapartnerthrough.json
- backend/hct_mis_api/apps/core/management/commands/initdemo.py
- backend/hct_mis_api/apps/program/fixtures/programpartnerthrough.json
[AB#200948](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/200948)
> [200948] Update initdemo for new partner structure

- backend/hct_mis_api/api/endpoints/rdi/push_people.py
- backend/hct_mis_api/api/tests/test_push_people.py
[AB#201378](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/201378)
> [201378] Fix api, push admin1, admin2

- backend/hct_mis_api/one_time_scripts/assign_program_to_grievance_tickets.py
- backend/hct_mis_api/one_time_scripts/tests/test_grievance_ticket_fill_empty_program.py
- frontend/src/components/grievances/CreateGrievance/Description/Description.tsx
- frontend/src/containers/pages/accountability/feedback/CreateFeedbackPage.tsx
[AB#201273](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/201273)
> [HOTFIX][201273] Fix Grievance creation flow for All Programs, fix existing Grievances

- frontend/src/containers/tables/rdi/ImportedPeopleTable/ImportedPeopleTableRow.tsx
- frontend/src/containers/tables/rdi/ImportedPeopleTable/__snapshots__/ImportedPeopleTable.test.tsx.snap
[AB#201986](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/201986): Grey Page when accessing a People imported by API
> [STG]201986 fix url rdi not merged people details page

- frontend/src/components/managerialConsole/ApprovalSection.tsx
- frontend/src/components/managerialConsole/AuthorizationSection.tsx
- frontend/src/components/managerialConsole/PendingForReleaseSection.tsx
- frontend/src/components/managerialConsole/ReleasedSection.tsx
- frontend/src/components/managerialConsole/useSortAndFilter.tsx
- frontend/src/components/rdi/create/xlsx/CreateImportFromXlsxForm.tsx
[AB#200401](https://unicef.visualstudio.com/ICTD-HCT-MIS/_boards/board/t/HOPE%20Team/Stories/?workitem=200401)
> [200401]-managerial console - add group by program filter + sorting in released section

- backend/hct_mis_api/apps/payment/admin.py
[AB#202109](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/202109)
> fix_fsp_admin_update_validation

- backend/hct_mis_api/apps/grievance/tests/test_grievance_es.py
- backend/pdm.lock
- backend/pyproject.toml
- elasticsearch/Dockerfile
[AB#201818](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/201818)
> AB#201818 elasticsearch fix

- backend/hct_mis_api/apps/payment/services/payment_gateway.py
[AB#201803](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/201803)
> AB#201803 add delivery mechanism to payment gateway

- backend/hct_mis_api/apps/core/utils.py
- backend/hct_mis_api/apps/household/schema.py
- backend/hct_mis_api/apps/household/tests/snapshots/snap_test_dashboard_queries.py
- backend/hct_mis_api/apps/household/tests/test_dashboard_queries.py
- backend/selenium_tests/drawer/test_drawer.py
- frontend/data/schema.graphql
- frontend/package.json
- frontend/src/__generated__/graphql.tsx
- frontend/src/apollo/queries/reporting/dashboard/AllCharts.ts
- frontend/src/components/core/Drawer/menuItems.tsx
- frontend/src/components/dashboard/TotalAmountTransferredByAdminAreaTable.tsx
- frontend/src/components/dashboard/sections/PaymentVerificationSection/PaymentVerificationSection.test.tsx
- frontend/src/components/dashboard/sections/PaymentVerificationSection/PaymentVerificationSection.tsx
- frontend/src/components/dashboard/sections/TotalAmountTransferredByAdminAreaForPeopleSection/TotalAmountTransferredByAdminAreaForPeopleSection.tsx
- frontend/src/components/dashboard/sections/TotalAmountTransferredByAdminAreaForPeopleSection/TotalAmountTransferredByAdminAreaTableForPeople.tsx
- frontend/src/components/dashboard/sections/TotalAmountTransferredByAdminAreaForPeopleSection/index.ts
- frontend/src/components/dashboard/sections/TotalAmountTransferredByAdminAreaSection/TotalAmountTransferredByAdminAreaSection.tsx
- frontend/src/components/dashboard/sections/TotalAmountTransferredByAdminAreaSection/TotalAmountTransferredByAdminAreaTable.tsx
- frontend/src/components/dashboard/sections/TotalAmountTransferredByCountrySection/TotalAmountTransferredByCountrySection.tsx
- frontend/src/components/dashboard/sections/TotalNumberOfChildrenReachedSection/TotalNumberOfChildrenReachedSection.tsx
- frontend/src/components/dashboard/sections/TotalNumberOfPeopleReachedSection/TotalNumberOfPeopleReachedSection.tsx
- frontend/src/components/dashboard/sections/TotalNumberOfPeopleReachedSection/index.ts
- frontend/src/containers/pages/dashboard/DashboardPage.tsx
- frontend/src/containers/pages/dashboard/DashboardYearPage.tsx
- frontend/yarn.lock
[AB#197179](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/197179)
> [197179] Dashboard people changes

- frontend/src/containers/GlobalProgramSelect.tsx
[AB#201654](https://dev.azure.com/unicef/ICTD-HCT-MIS/_workitems/edit/201654)
> [201654]-Load program list on focus to show newly created program

- frontend/src/containers/pages/program/CreateProgramPage.tsx
- frontend/src/containers/pages/program/DuplicateProgramPage.tsx
- frontend/src/containers/pages/program/EditProgramPage.tsx
[AB#202614](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/202614)
> [202614] Fix edge case for validate Program end date

- frontend/src/components/targeting/EditTargetPopulation/EditTargetPopulation.tsx
- frontend/src/components/targeting/TargetingCriteria/TargetingCriteria.tsx
- frontend/src/containers/pages/targeting/CreateTargetPopulationPage.tsx
[AB#203070](https://unicef.visualstudio.com/ICTD-HCT-MIS/_boards/board/t/HOPE%20Team/Stories/?workitem=203070)
> [203070]-change sanction list flag text based on dct type in targeting

- backend/hct_mis_api/apps/household/models.py
- backend/hct_mis_api/apps/household/tests/test_models.py
- backend/hct_mis_api/apps/payment/tests/test_import_export_payment_plan_payment_list.py
- backend/hct_mis_api/apps/payment/xlsx/xlsx_payment_plan_export_per_fsp_service.py
[AB#202742](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/202742): Payment Module: Payment list is not populated with some fields
> [202742] Payment list is not populated with some fields

- frontend/src/containers/tables/paymentmodule/PaymentsTable/PaymentsTableHeadCells.tsx
- frontend/src/containers/tables/paymentmodulePeople/PeoplePaymentsTable/PeoplePaymentsTableHeadCells.tsx
- frontend/src/containers/tables/paymentmodulePeople/PeoplePaymentsTable/PeoplePaymentsTableRow.tsx
[AB#198870](https://unicef.visualstudio.com/ICTD-HCT-MIS/_boards/board/t/HOPE%20Team/Stories/?workitem=198870)
> [198870]-Fix/people fsp auth code

- frontend/src/api/paymentModuleApi.ts
[AB#203395](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/203395)
> [203395] Remove limit for payment plans list in Managerial Console

- backend/hct_mis_api/apps/grievance/notifications.py
[AB#203434](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/203434)
> [203434] Fix url in grievance notification

- frontend/src/components/paymentmodule/PaymentPlanDetails/FspSection/VolumeByDeliveryMechanismSection/VolumeByDeliveryMechanismSection.tsx
- frontend/src/components/paymentmodulepeople/PaymentPlanDetails/FspSection/VolumeByDeliveryMechanismSection/VolumeByDeliveryMechanismSection.tsx
[AB#200867](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/200867)
> [200867] Payment Module - Label for delivery mechanism is corrupted

- frontend/src/components/payments/CreateVerificationPlan.tsx
- frontend/src/components/payments/EditVerificationPlan.tsx
- frontend/src/components/payments/RapidProFlowsLoader.tsx
- frontend/src/components/payments/VerificationPlanActions.tsx
- frontend/src/components/rdi/create/xlsx/CreateImportFromXlsxForm.tsx
- frontend/src/containers/pages/payments/CashPlanVerificationDetailsPage.tsx
- frontend/src/containers/pages/payments/PaymentPlanVerificationDetailsPage.tsx
[AB#203270](https://unicef.visualstudio.com/ICTD-HCT-MIS/_boards/board/t/HOPE%20Team/Stories/?workitem=203270)
> 🔥hotfix [203270] - access denied in create/edit payment verification dialogs

- frontend/src/components/grievances/GrievanceDetailsToolbar.tsx
- frontend/src/components/payments/CreateVerificationPlan.tsx
- frontend/src/components/payments/EditVerificationPlan.tsx
[AB#203821](https://unicef.visualstudio.com/ICTD-HCT-MIS/_boards/board/t/HOPE%20Team/Stories/?workitem=203821)
[AB#203393](https://unicef.visualstudio.com/ICTD-HCT-MIS/_boards/board/t/HOPE%20Team/Stories/?workitem=203393)
> [203821, 203393]- fix rapid pro flows not showing up in create/ edit verification, wrong alert in Grievance

- backend/hct_mis_api/apps/core/schema.py
- backend/hct_mis_api/apps/program/models.py
- backend/hct_mis_api/apps/program/schema.py
- backend/hct_mis_api/apps/program/tests/snapshots/snap_test_all_programs_query.py
- backend/hct_mis_api/apps/program/tests/test_all_programs_query.py
- frontend/data/schema.graphql
- frontend/src/__generated__/graphql.tsx
[AB#202127](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/202127): Unexpected Error when loading Programmes for Ukraine
> All Programs query optimization

- backend/hct_mis_api/apps/grievance/services/needs_adjudication_ticket_services.py
- backend/hct_mis_api/apps/grievance/tests/test_create_needs_adjudication_tickets.py
- backend/hct_mis_api/apps/registration_datahub/tasks/rdi_merge.py
[AB#203793](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/203793): Haiti: Needs adjudication tickets created for the same individual
> Fix Needs adjudication tickets created for the same individual

- backend/hct_mis_api/apps/household/models.py
- backend/hct_mis_api/one_time_scripts/fix_disability_fields.py
- backend/hct_mis_api/one_time_scripts/tests/test_fix_disability_fields.py
[AB#202642](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/202642)
> [202642] Disability is not populated systematically

- backend/hct_mis_api/apps/core/admin.py
- backend/hct_mis_api/apps/core/apps.py
- backend/hct_mis_api/apps/core/forms.py
- backend/hct_mis_api/apps/core/models.py
- backend/hct_mis_api/apps/core/signals.py
- backend/hct_mis_api/apps/core/tests/test_admin.py
- backend/hct_mis_api/apps/core/tests/test_data_collecting_type_validation.py
[AB#204129](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/204129)
> [204129] Do not allow dct compatibility between different types

- backend/hct_mis_api/apps/registration_datahub/tasks/rdi_kobo_create.py
[AB#200869](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/200869)
> [200869] stg - issuing country and document number is not required

- backend/hct_mis_api/apps/grievance/services/data_change/utils.py
- backend/hct_mis_api/apps/grievance/tests/services/data_change/test_add_individual_service.py
- backend/hct_mis_api/apps/grievance/tests/services/data_change/test_update_individual_data_service.py
- backend/hct_mis_api/apps/household/tests/test_models.py
[AB#203897](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/203897)
> [203897] Fix documents uniqueness validation in Grievance tickets flow

- frontend/src/components/targeting/EditTargetPopulation/EditTargetPopulation.tsx
- frontend/src/components/targeting/TargetingCriteria/TargetingCriteria.tsx
- frontend/src/containers/pages/targeting/CreateTargetPopulationPage.tsx
- frontend/src/shared/Formik/FormikCheckboxField/FormikCheckboxField.tsx
- frontend/src/utils/en.json
additional fix for:
[AB#203070](https://unicef.visualstudio.com/ICTD-HCT-MIS/_boards/board/t/HOPE%20Team/Stories/?workitem=203070)
> [203070]-fix labels targeting sanction screen flag

- backend/hct_mis_api/apps/core/utils.py
- backend/hct_mis_api/apps/household/schema.py
- backend/hct_mis_api/apps/household/tests/snapshots/snap_test_dashboard_queries.py
- backend/hct_mis_api/apps/payment/schema.py
- backend/hct_mis_api/apps/payment/services/dashboard_service.py
- backend/hct_mis_api/apps/payment/tests/services/test_dashboard_service.py
- backend/hct_mis_api/apps/payment/tests/snapshots/snap_test_dashboard_queries.py
- backend/hct_mis_api/apps/payment/tests/test_dashboard_queries.py
- backend/hct_mis_api/apps/program/schema.py
- backend/hct_mis_api/apps/program/signals.py
- backend/hct_mis_api/apps/utils/schema.py
- backend/selenium_tests/payment_module/test_payment_module.py
- frontend/data/schema.graphql
- frontend/src/__generated__/graphql.tsx
- frontend/src/apollo/queries/reporting/dashboard/AllCharts.ts
- frontend/src/apollo/queries/reporting/dashboard/CountryCharts.ts
- frontend/src/components/dashboard/charts/PaymentVerificationChart.tsx
- frontend/src/components/dashboard/charts/TotalTransferredByMonth.tsx
- frontend/src/components/dashboard/sections/PaymentVerificationSection/PaymentVerificationSection.test.tsx
- frontend/src/components/dashboard/sections/PaymentVerificationSection/__snapshots__/PaymentVerificationSection.test.tsx.snap
- frontend/src/components/dashboard/sections/PaymentVerificationSectionForPeople/PaymentVerificationSectionForPeople.tsx
- frontend/src/components/dashboard/sections/PaymentVerificationSectionForPeople/index.ts
- frontend/src/components/dashboard/sections/TotalAmountTransferredByAdminAreaForPeopleSection/TotalAmountTransferredByAdminAreaForPeopleSection.tsx
- frontend/src/components/dashboard/sections/TotalAmountTransferredByAdminAreaForPeopleSection/TotalAmountTransferredByAdminAreaTableForPeople.tsx
- frontend/src/containers/pages/dashboard/DashboardYearPage.tsx
[AB#203408](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/203408): Dashboard - Payment Verification figures are not reflected
[AB#197179](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/197179): Country Dashboard [People]
[AB#203509](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/203509): Country Dashboard - Total amount transferred is showing zero
[AB#201888](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/201888): Hope dashboard not displaying correct figures
> Dashboard fixes

- .github/workflows/ci.yml
[AB#204266](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/204266)
> Set concurrency group for CI pipeline

- backend/hct_mis_api/apps/payment/tests/test_payment_plan_reconciliation.py
- backend/hct_mis_api/apps/payment/xlsx/xlsx_payment_plan_per_fsp_import_service.py
[AB#206265](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/206265)
> 206265 Belarus: XLSX Import error

- backend/hct_mis_api/apps/core/tests/test_utils.py
- backend/hct_mis_api/apps/payment/models.py
- backend/hct_mis_api/apps/payment/services/payment_gateway.py
- backend/hct_mis_api/apps/payment/tests/test_models.py
- backend/hct_mis_api/apps/payment/tests/test_payment_gateway_service.py
- backend/hct_mis_api/apps/payment/utils.py
- backend/hct_mis_api/apps/payment/xlsx/xlsx_payment_plan_per_fsp_import_service.py
- frontend/data/schema.graphql
- frontend/src/__generated__/graphql.tsx
- frontend/src/utils/utils.ts
[AB#199072](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/199072)
> 199072_Add_Payment_Status_and_move_mapping_from_PG_to_HOPE

- backend/hct_mis_api/apps/household/migrations/0178_migration.py
> Migrations fix after Removig datahub

- backend/hct_mis_api/apps/targeting/mutations.py
- backend/hct_mis_api/apps/targeting/tests/snapshots/snap_test_create_target_population_mutation.py
- backend/hct_mis_api/apps/targeting/tests/test_create_target_population_mutation.py
- backend/hct_mis_api/apps/targeting/tests/test_targeting_validators.py
- backend/hct_mis_api/apps/targeting/validators.py
[AB#203133](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/203133)
> [203133] Fix create tp with not existing hh ids

- backend/hct_mis_api/one_time_scripts/mass_withdraw_sudan_hhs.py
- backend/hct_mis_api/one_time_scripts/tests/test_mass_withdraw_sudan_hhs.py
[AB#207915](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/207915)
> [HOTFIX] 207915: mass withdraw households and individuals from sudan

- backend/hct_mis_api/apps/registration_datahub/tasks/rdi_kobo_create.py
[AB#208169](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/208169)
https://monitoring.hope.unicef.org/organizations/hope/issues/4848/?project=4&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
> [208169] Fix kobo import

- backend/hct_mis_api/apps/household/documents.py
- backend/hct_mis_api/apps/payment/tests/test_payment_gateway_service.py
- backend/hct_mis_api/apps/registration_data/admin.py
- backend/hct_mis_api/apps/registration_data/tests/test_admin.py
[AB#208274](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/208274)
> [208274] Amend button to remove RDI in admin

- backend/hct_mis_api/aurora/services/ukraine_flex_registration_service.py
[AB#208943](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/208943)
> 208943 fix aurora import

- backend/hct_mis_api/apps/household/services/individual_xlsx_update.py
[AB#208689](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/208689): Not possible to import XLSX import file
the issue was that we have column name `individual__individual_unicef_id` but on the Individual model we have just `unicef_id`
> [HOTFIX] Fix issue with xlsx update Ind `unicef_id` column name

- backend/hct_mis_api/apps/core/utils.py
- backend/hct_mis_api/apps/grievance/models.py
- backend/hct_mis_api/apps/household/admin/household.py
- backend/hct_mis_api/apps/household/celery_tasks.py
- backend/hct_mis_api/apps/household/templates/admin/household/household/withdraw_households_from_list.html
- backend/hct_mis_api/apps/household/tests/test_household_admin.py
[AB#208150](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/208150)
> [208150] Add admin action - withdraw households by IDs in list

- backend/hct_mis_api/apps/household/services/individual_xlsx_update.py
- backend/hct_mis_api/aurora/services/ukraine_flex_registration_service.py
* 208943 fix aurora import (#4069)
* fix issue with Ind unicef_id column name (#4067)
---------
> back staging

- backend/hct_mis_api/api/tests/test_humanize.py
- backend/hct_mis_api/apps/household/migrations/0148_migration_squashed_0169_migration.py
- backend/hct_mis_api/apps/household/models.py
- backend/hct_mis_api/aurora/admin.py
[AB#208943](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/208943)
> 208943 aurora hf

- backend/hct_mis_api/apps/household/templates/admin/household/household/withdraw_households_from_list.html
[AB#209263](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/209263)
> [209263] Remove duplicate header for withdraw hhs for list

- backend/hct_mis_api/apps/payment/models.py
- backend/hct_mis_api/apps/payment/tests/test_models.py
[AB#209655](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/209655)
> 209655 Payment Module - Getting AttributeError: 'PaymentPlanSplit' object has no attribute 'delivery_mechanism' when splitting payment

- backend/hct_mis_api/apps/registration_datahub/tasks/validate_xlsx_import.py
- backend/hct_mis_api/apps/registration_datahub/tests/test_validate_xlsx_import_task.py
- compose.yml
[AB#207805](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/207805)
> [207805] Getting an error at RDI details post import

- backend/hct_mis_api/apps/core/models.py
- backend/hct_mis_api/apps/core/tests/snapshots/snap_test_schema.py
- backend/hct_mis_api/apps/periodic_data_update/service/periodic_data_update_import_service.py
[AB#211115](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/211115)
> AB#211115 correct validation for boolean field

- backend/hct_mis_api/apps/program/api/serializers.py
- backend/hct_mis_api/apps/program/api/views.py
- backend/hct_mis_api/apps/program/models.py
- backend/hct_mis_api/apps/program/tests/test_program_cycle_rest_api.py
- frontend/src/api/programCycleApi.ts
- frontend/src/containers/pages/paymentmodule/ProgramCycle/ProgramCycleDetails/ProgramCycleDetailsHeader.tsx
- frontend/src/containers/tables/ProgramCycle/ProgramCycleTable.tsx
[AB#211998](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/211998)
> Add link to admin

- backend/hct_mis_api/apps/periodic_data_update/service/periodic_data_update_import_service.py
- backend/hct_mis_api/apps/periodic_data_update/tests/test_periodic_data_update_import_service.py
- backend/hct_mis_api/apps/registration_datahub/tasks/rdi_xlsx_create.py
[AB#212207](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/212207)
> [212207] PDU - fix values of DECIMAL type not to be stored as string

- frontend/src/components/rdi/create/kobo/CreateImportFromKoboForm.tsx
[AB#212079](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/212079)
> Make check-box "Pull Pictures" automatically checked when importing from Kobo

- backend/hct_mis_api/apps/account/tests/test_partner_permissions.py
- backend/hct_mis_api/apps/geo/tests/test_signal_create_area.py
- backend/hct_mis_api/apps/grievance/tests/test_filter_grievance_by_cross_area.py
- backend/hct_mis_api/apps/program/tests/test_copy_program.py
- backend/hct_mis_api/apps/program/tests/test_create_program.py
- backend/hct_mis_api/apps/program/tests/test_signal_partner_access_change.py
- backend/hct_mis_api/apps/program/tests/test_signal_partner_full_area_access_flag.py
- backend/hct_mis_api/apps/program/tests/test_update_program.py
- backend/hct_mis_api/one_time_scripts/tests/test_migrate_partner_permissions_and_access.py
- backend/tests/apps/geo/test_area_views.py
[AB#212854](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/212854)
> Fix unstable test and other potentially unstable tests

- backend/hct_mis_api/apps/targeting/mutations.py
- backend/hct_mis_api/apps/targeting/tests/snapshots/snap_test_copy_target_population_mutation.py
- backend/hct_mis_api/apps/targeting/tests/test_copy_target_population_mutation.py
[AB#205783](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/205783)
> [205783] Fix copy targeting based on IDs

- backend/hct_mis_api/apps/program/mutations.py
- backend/hct_mis_api/apps/program/tests/snapshots/snap_test_update_program.py
- backend/hct_mis_api/apps/program/tests/test_update_program.py
- backend/hct_mis_api/one_time_scripts/program_cycle_data_migration.py
[AB#213284](https://dev.azure.com/unicef/ICTD-HCT-MIS/_workitems/edit/213284): Programme cycle - unexpected error when accessing programme cycle for new programme
> [STG] Cycles fixes

- backend/hct_mis_api/apps/targeting/mutations.py
- backend/hct_mis_api/apps/targeting/tests/test_copy_target_population_mutation.py
[AB#203671](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/203671)
> Strip name in copy targeting

- backend/hct_mis_api/one_time_scripts/program_cycle_data_migration.py
[AB#213853](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/213853): Targeting - Error when attempting to edit an old TP
> [STG] Fix cycle migrations TP without payment plan

- frontend/src/components/grievances/CreateGrievance/Selection/Selection.tsx
- frontend/src/components/grievances/utils/validateGrievance.ts
- frontend/src/containers/pages/accountability/feedback/CreateFeedbackPage.tsx
[AB#209087](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/209087)
> Prevent to press the next button without choosing category.

- backend/hct_mis_api/apps/grievance/tests/test_grievance_create_complaint_ticket.py
- frontend/src/containers/BusinessAreaSelect.tsx
[AB#214408](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/214408)
> Clear cache on change business area

- backend/selenium_tests/grievance/grievance_tickets/test_grievance_tickets.py
- frontend/src/components/grievances/utils/validationSchema.ts
[AB#212619](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/212619)
> Unable to create Payment Related Complaint ticket

- backend/hct_mis_api/apps/program/apps.py
[AB#212802](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/212802)
> Fix program size signals

- src/hct_mis_api/apps/registration_datahub/validators.py
- tests/selenium/programme_management/test_programme_management.py
- tests/unit/apps/registration_datahub/test_kobo_validators_methods.py
[AB#215364](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/215364)
> [215364] KOBO - Add validation for unique individual with role in household

- src/frontend/src/containers/pages/paymentmodule/ProgramCycle/ProgramCycleDetails/PaymentPlansHeadCells.ts
- src/frontend/src/containers/pages/paymentmodule/ProgramCycle/ProgramCycleDetails/ProgramCycleDetailsHeader.tsx
[AB#216921](https://dev.azure.com/unicef/ICTD-HCT-MIS/_workitems/edit/216921)
> [AB#216921]-remove usd from label

- src/frontend/src/components/core/Drawer/Drawer.tsx
- src/frontend/src/components/core/Drawer/DrawerItems.tsx
- src/frontend/src/containers/GlobalProgramSelect.tsx
[AB#200744](https://unicef.visualstudio.com/ICTD-HCT-MIS/_boards/board/t/HOPE%20Team/Stories/?workitem=200744)
> AB#200744 - access denied on programs list

- backend/hct_mis_api/apps/program/utils.py
- backend/hct_mis_api/apps/registration_datahub/tests/test_program_population_to_pending_objects.py
[AB#217083](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/217083): Ukraine- Merge error with no detials
> [HOTFIX] Fix Document status RDI program population

- src/hct_mis_api/apps/registration_data/nodes.py
- src/hct_mis_api/apps/registration_data/schema.py
- src/hct_mis_api/apps/registration_datahub/services/biometric_deduplication.py
[AB#217643](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/217643)
[AB#217649](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/217649)
[AB#217625](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/217625)
> staging_tests_dedupe_integration_fixes

- src/hct_mis_api/apps/registration_data/models.py
- src/hct_mis_api/apps/registration_data/nodes.py
- src/hct_mis_api/apps/registration_datahub/services/biometric_deduplication.py
[AB#217643](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/217643)
> Staging tests dedupe integration fixes

- src/hct_mis_api/one_time_scripts/remove_migrated_data_is_original.py
[AB#204353](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/204353): Clean/Remove pre GPF data
added `.only()` & `.iterator()`
> Clean/Remove pre GPF data: Script Optimization

- src/hct_mis_api/api/endpoints/core/views.py
- src/hct_mis_api/api/endpoints/rdi/program.py
[AB#217273](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/217273)
> [217273] REST API updates - review changes 

- src/hct_mis_api/one_time_scripts/remove_migrated_data_is_original.py
- tests/unit/one_time_scripts/test_remove_migrated_data_is_original.py
[AB#204353](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/204353): Clean/Remove pre GPF data
updated `remove_migrated_data_is_original()` 
and  added just for statistics `get_statistic_is_original()`
> Optimization script remove data with `is_original=True` v3

- src/hct_mis_api/apps/registration_datahub/celery_tasks.py
- src/hct_mis_api/apps/registration_datahub/tasks/deduplicate.py
- src/hct_mis_api/apps/registration_datahub/tasks/rdi_merge.py
- tests/unit/apps/registration_datahub/test_deduplication.py
- tests/unit/apps/registration_datahub/test_handling_documents_duplicates.py
[AB#218877](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/218877)
> hotfix_218648_RDI_in_Merge_Error_Status_documents_deduplication

- development_tools/compose.yml
- docker/entrypoint.sh
- pdm.lock
- pyproject.toml
[AB#218394](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/218394): celery-flower entrypoint
> Add flower entrypoint 🌷 🌹 

- src/hct_mis_api/apps/household/fixtures.py
- src/hct_mis_api/apps/payment/managers.py
- src/hct_mis_api/apps/program/utils.py
- src/hct_mis_api/one_time_scripts/fix_program_population_import_incorrect_hh_ind_relation.py
- tests/unit/apps/payment/test_models1.py
- tests/unit/apps/registration_datahub/test_program_population_to_pending_objects.py
- tests/unit/one_time_scripts/test_fix_program_population_import_incorrect_hh_ind_relation.py
[AB#219583](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/219583)
[AB#219514](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/219514): Duplicate HH in Payment plan-Palestine
Exclude Payment Plan` is_removed=True`
> [219583] [HOTFIX] Fix ImportProgramPopulation hh assignment, one-time-script to fix prod data && Payment conflicts PR#4370

- src/hct_mis_api/one_time_scripts/remove_production_duplicates_after_enrollment.py
- tests/unit/one_time_scripts/test_remove_production_duplicates_after_enrollment.py
[AB#217947](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/217947)
[AB#219050](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/219050)
> [217947] Remove the incorrect duplicates after enrollment

- src/hct_mis_api/api/endpoints/lookups/area.py
- src/hct_mis_api/api/endpoints/lookups/base.py
- src/hct_mis_api/api/filters.py
- tests/unit/api/test_lookups.py
[AB#220022](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/220022)
> [220022] Geo api search and filter

- src/frontend/src/components/grievances/PaymentGrievance/PaymentGrievanceDetails/PaymentGrievanceDetails.tsx
[AB#219996](https://dev.azure.com/unicef/ICTD-HCT-MIS/_workitems/edit/219996)
> [219996]-Cannot open payment verification details GF

- pyproject.toml
- src/hct_mis_api/apps/grievance/services/needs_adjudication_ticket_services.py
- tests/unit/apps/grievance/test_services_utils.py
[AB#220122](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/220122)
[AB#219858](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/219858)
> [220122] [HOTFIX] Prevent errors when individual has no household

- src/hct_mis_api/apps/program/schema.py
https://monitoring.hope.unicef.org/organizations/hope/issues/7660/?alert_rule_id=8&alert_timestamp=1730725726461&alert_type=email&environment=production&notification_uuid=a5b959f2-8483-420b-b32b-37e668b95627&project=4&referrer=alert_email
> hotfix_disable_biometrics_schema_for_all_programs

- src/frontend/src/containers/pages/people/PeopleDetailsPage.tsx
[AB#201639](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/201639)
> [201639]-add Delivery Mechanism section for people

- .github/workflows/ci.yml
[AB#221270](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/221270)
> Upgrade actions version

- src/hct_mis_api/config/env.py
[AB#222138](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/222138)
> [222138] Emails - fix type for DEFAULT_EMAIL_DISPLAY

- src/frontend/src/components/paymentmodule/EditPaymentPlan/EditPaymentPlanHeader/EditPaymentPlanHeader.tsx
- src/frontend/src/components/paymentmodule/EditPaymentPlan/EditPaymentPlanHeader/__snapshots__/EditPaymentPlanHeader.test.tsx.snap
- src/frontend/src/components/paymentmodule/FollowUpPaymentPlanDetails/FollowUpPaymentPlanDetailsHeader/FollowUpPaymentPlanDetailsHeader.tsx
- src/frontend/src/components/paymentmodulepeople/EditPaymentPlan/EditPaymentPlanHeader/EditPaymentPlanHeader.tsx
- src/frontend/src/components/paymentmodulepeople/EditPaymentPlan/EditPaymentPlanHeader/__snapshots__/EditPaymentPlanHeader.test.tsx.snap
- src/frontend/src/components/paymentmodulepeople/FollowUpPaymentPlanDetails/FollowUpPaymentPlanDetailsHeader/FollowUpPaymentPlanDetailsHeader.tsx
- src/frontend/src/containers/pages/headers/TargetPopulationPageHeader.tsx
- src/frontend/src/containers/pages/paymentmodule/ProgramCycle/PaymentPlanDetails/PaymentPlanDetailsHeader.tsx
[#AB221685](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/221685)
> [#AB221685]-fix status label width payment plan details page

- src/hct_mis_api/apps/dashboard/serializers.py
- src/hct_mis_api/apps/dashboard/services.py
- src/hct_mis_api/apps/dashboard/static/dashboard/css/dashboard.css
- src/hct_mis_api/apps/dashboard/templates/dashboard/dashboard.html
- tests/selenium/country_dashboard/test_country_dashboard.py
- tests/selenium/page_object/country_dashboard/country_dashboard.py
- tests/unit/apps/dashboard/test_services.py
- tests/unit/fixtures/dashboard.py
[AB#222792](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/222792)
> Updated dashboard

- src/hct_mis_api/apps/registration_datahub/apis/deduplication_engine.py
- src/hct_mis_api/apps/registration_datahub/services/biometric_deduplication.py
- tests/unit/apps/registration_datahub/test_biometric_deduplication_service.py
- tests/unit/apps/registration_datahub/test_deduplication_engine_api.py
[AB#223262](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/223262)
> 223262_Remove_configuration_sent_to_Dedup

- src/hct_mis_api/apps/geo/fixtures/data.json
- src/hct_mis_api/apps/geo/schema.py
- src/hct_mis_api/apps/program/admin.py
- tests/unit/apps/core/snapshots/snap_test_all_fields_attributes_query.py
- tests/unit/apps/geo/snapshots/snap_test_schema.py
- tests/unit/apps/geo/test_schema.py
[AB# 224091](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/224091): Programme Management - System is hanging when assigning/adding partners
> [HOTFIX] allAreasTree query filter by max area_level  3

- development_tools/compose.yml
[AB#217078](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/217078)
> rename es container name

- src/hct_mis_api/apps/payment/admin.py
[AB#228219](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/228219)
> 228219_fincacial_service_provider_admin_fix

- src/hct_mis_api/apps/program/utils.py
- tests/unit/apps/registration_datahub/test_program_population_to_pending_objects.py
[AB#229053](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/229053)
[AB#229278](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/229278)
> [HOTFIX] Import Program Population - fix for individuals without households after recent changes

- src/hct_mis_api/one_time_scripts/migrate_tp_into_pp.py
- tests/unit/one_time_scripts/test_migrate_tp_into_pp.py
[AB#215785](https://dev.azure.com/unicef/ICTD-HCT-MIS/_workitems/edit/215785): Adjust PaymentPlan model to contain informations coming from TP and HS
`For FollowUp PP we need to create targeting_criteria copy`
> DEV update migration script TP>PP

- pyproject.toml
- src/frontend/package.json
- src/hct_mis_api/apps/program/utils.py
- tests/unit/apps/registration_datahub/test_program_population_to_pending_objects.py
[AB#229798](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/229798)
> [HOTFIX] Import program population - exclude roles on withdrawn/duplicate individuals

- src/frontend/src/containers/pages/paymentmodule/ProgramCycle/ProgramCycleDetails/ProgramCycleDetailsHeader.tsx
- src/frontend/src/containers/tables/ProgramCycle/DeleteProgramCycle.tsx
- src/frontend/src/containers/tables/ProgramCyclesTable/ProgramCyclesTable.tsx
- src/frontend/src/containers/tables/ProgramCyclesTablePaymentModule/ProgramCyclesTablePaymentModule.tsx
> Revert "[hotfix]/for each error"

- src/frontend/src/containers/tables/rdi/ImportedIndividualsTable/ImportedIndividualsTableRow.tsx
- src/frontend/src/containers/tables/rdi/ImportedPeopleTable/ImportedPeopleTableRow.tsx
[AB#231034](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/231034)
> fix biometric golden record results

- src/hct_mis_api/apps/payment/services/payment_gateway.py
[AB#234214](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/234214)
> send middlename

- pyproject.toml
- src/frontend/package.json
- src/frontend/src/components/grievances/EditPeopleDataChange/EditPeopleDataChange.tsx
[`AB#234220`](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/234220)
>  🔥hotfix-[AB#234220]-add edit payment channel to people data change

- src/frontend/src/components/grievances/CreateGrievance/Description/Description.tsx
- src/frontend/src/components/grievances/EditIndividualDataChange/EditIndividualDataChange.tsx
- src/frontend/src/components/grievances/EditPeopleDataChange/EditPeopleDataChange.tsx
- src/frontend/src/containers/pages/grievances/EditGrievancePage.tsx
- src/frontend/src/utils/en.json
[AB#233871](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/233871)
> [AB#233871]-add description to documents, documentation labels

- src/frontend/src/components/grievances/LookUps/LookUpIndividualTable/LookUpIndividualTable.tsx
[AB#231294](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/231294): Possible to change the data of a withdrawn individual
> Grievance LookUp Individual Table add `withdrawn: false` filter

- src/frontend/src/components/grievances/LookUps/LookUpIndividualTable/LookUpIndividualTable.tsx
[AB#231294](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/231294): Possible to change the data of a withdrawn individual
> STG //  Grievance LookUp Individual Table add withdrawn: false filter

- src/frontend/src/components/programs/CreateProgram/PartnersStep.tsx
- src/frontend/src/components/programs/EditProgram/PartnersStep.tsx
- src/frontend/src/containers/pages/program/CreateProgramPage.tsx
- src/frontend/src/containers/pages/program/DuplicateProgramPage.tsx
- src/frontend/src/containers/pages/program/EditProgramPage.tsx
[AB-224937](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/224937)
> [AB#224937]-loading button program

- src/frontend/src/components/grievances/LookUps/LookUpIndividualTable/LookUpIndividualTable.tsx
- src/frontend/src/containers/tables/people/PeopleListTable/PeopleListTable.tsx
[AB#230447](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/230447): Madagascar: Cannot close estimated birth date change grievance ticket
> STG Fix population default filters [Rdi merge status]

- pyproject.toml
- src/frontend/package.json
- src/frontend/src/containers/tables/targeting/TargetPopulationForPeopleTable/TargetPopulationForPeopleTable.tsx
[AB#237370](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/237370/)
> 🔥hotfix -[AB#237370]- Old TPs not appearing in the targeting module for all Social Workers Programme

- pyproject.toml
- src/frontend/package.json
- src/hct_mis_api/apps/account/admin/ad.py
[AB#237470](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/237470): Admin - Error when loading new users
> Hotfix 237470 Admin load AD users

- pyproject.toml
- src/frontend/package.json
- src/frontend/src/containers/pages/people/PeopleDetailsPage.tsx
- src/frontend/src/containers/pages/population/PopulationHouseholdDetailsPage.tsx
[AB#237764](https://dev.azure.com/unicef/ICTD-HCT-MIS/_workitems/edit/237764)
> 🔥hotfix-fix permission HH/People details section Payments Table

- src/frontend/src/shared/Formik/FormikSliderField/FormikSliderField.tsx
[AB#238960](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/238960)
> [AB#238960]-fix slider field not displaying

- src/frontend/src/containers/tables/paymentmodulePeople/PeoplePaymentsTable/PeoplePaymentsTableHeadCells.tsx
- src/frontend/src/containers/tables/paymentmodulePeople/PeoplePaymentsTable/PeoplePaymentsTableRow.tsx
- src/frontend/src/containers/tables/paymentmodulePeople/PeoplePaymentsTable/__snapshots__/PeoplePaymentsTable.test.tsx.snap
[#AB241931](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/241931)
> [#AB241931]-fix payment status

- src/frontend/src/__generated__/graphql.tsx
- src/frontend/src/apollo/queries/paymentmodule/AllPaymentPlansForTable.ts
- src/frontend/src/containers/tables/payments/PaymentVerificationTable/PaymentVerificationTableRow.tsx
- tests/selenium/payment_verification/test_payment_verification.py
[AB#241732](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/241732)
> [AB#241732]-Fix pv status

- src/frontend/src/components/grievances/CreateGrievance/Description/Description.tsx
- src/frontend/src/components/grievances/CreateGrievance/Selection/Selection.tsx
- src/frontend/src/components/grievances/Documentation/DocumentationField.tsx
- src/frontend/src/components/grievances/Documentation/NewDocumentationFieldArray.tsx
- src/frontend/src/components/grievances/EditIndividualDataChange/EditIndividualDataChange.tsx
- src/frontend/src/components/grievances/EditPeopleDataChange/EditPeopleDataChange.tsx
- src/frontend/src/components/grievances/EditPeopleDataChange/EditPeopleDataChangeFieldRow.tsx
- src/frontend/src/components/grievances/GrievancesDetails/GrievancesDetails.tsx
- src/frontend/src/components/grievances/GrievancesDetails/__snapshots__/GrievancesDetails.test.tsx.snap
- src/frontend/src/components/grievances/Notes/Notes.tsx
- src/frontend/src/components/grievances/utils/validateGrievance.ts
- src/frontend/src/containers/pages/grievances/EditGrievancePage.tsx
- src/frontend/src/containers/tables/targeting/TargetPopulationPeopleTable/TargetPopulationPeopleRow.tsx
- src/frontend/src/utils/en.json
- tests/selenium/page_object/grievance/details_grievance_page.py
[AB#243258](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/243258/)
[AB#243260](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/243260/)
[AB#243337](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/243337)
[AB#243262](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/243262)
> Bugs 1.04.25

- src/frontend/src/components/targeting/TargetingCriteriaDisplay/AddFilterTargetingCriteriaDisplay.tsx
- src/frontend/src/components/targeting/TargetingCriteriaDisplay/Criteria.tsx
[#AB243341](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/243341)
> #AB243341/fsp tp

- src/hct_mis_api/apps/payment/api/caches.py
- src/hct_mis_api/apps/payment/api/serializers.py
- src/hct_mis_api/apps/payment/api/urls.py
- src/hct_mis_api/apps/payment/api/views.py
[AB#244519](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/244519): REST Payment Verification Backend
> WIP // Rest Payment Verification

- src/hct_mis_api/config/env.py
- src/hct_mis_api/config/settings.py
just allows customisation of GDAL_LIBRARY_PATH and GEOS_LIBRARY_PATH.
> allows GDAL location customisation

- src/hct_mis_api/apps/program/models.py
- src/hct_mis_api/apps/program/validators.py
- tests/unit/apps/core/test_schema.py
- tests/unit/apps/program/test_program_cycle_rest_api.py
- tests/unit/apps/program/test_validators.py
[AB#246752](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/246752): Nigeria - User can't close a programme cycle
> STG Fix Finish Cycle Validation

- src/hct_mis_api/apps/core/api/mixins.py
[AB#247295](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/247295)
> [247295] Swagger fix

- src/hct_mis_api/apps/targeting/models.py
- tests/unit/apps/payment/test_payment_plan_mutation.py
- tests/unit/apps/targeting/test_individual_block_filters.py
- tests/unit/apps/targeting/test_targeting_criteria_rule_filter.py
- tests/unit/apps/targeting/test_targeting_services_utils.py
[AB#248627](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/248627)
> 248580_Targeting_TP_is_failing_if_Collector_rule_is_applied

- src/frontend/src/components/grievances/EditHouseholdDataChange/EditHouseholdDataChange.tsx
- src/frontend/src/components/grievances/EditIndividualDataChange/EditIndividualDataChange.tsx
- src/frontend/src/components/grievances/EditPeopleDataChange/EditPeopleDataChange.tsx
[AB#241907](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/241907): Nigeria: Cannot update locations for Social Worker Programmes
> STG Grievance fields cache issue

- src/hct_mis_api/apps/core/tasks_schedules.py
- src/hct_mis_api/apps/dashboard/celery_tasks.py
- src/hct_mis_api/apps/dashboard/serializers.py
- src/hct_mis_api/apps/dashboard/services.py
- src/hct_mis_api/apps/dashboard/templates/dashboard/base_dashboard.html
- src/hct_mis_api/apps/dashboard/templates/dashboard/dashboard.html
- src/hct_mis_api/apps/dashboard/templates/dashboard/global_dashboard.html
- src/hct_mis_api/apps/dashboard/templates/dashboard/includes/metric_cards.html
- src/hct_mis_api/apps/dashboard/views.py
- tests/selenium/country_dashboard/test_country_dashboard.py
- tests/unit/apps/dashboard/test_services.py
- tests/unit/apps/dashboard/test_tasks.py
- tests/unit/apps/dashboard/test_views.py
- [AB#249413](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/249413)
- [AB#248262](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/248262)
- [AB#248261](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/248261)
> Dashboard enhachment

- src/frontend/src/components/targeting/TargetingCriteriaDisplay/Criteria.tsx
[253365](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/253365)
> [253365]-fix household ids / individual ids TP mismatch (stg)

- src/hct_mis_api/apps/payment/celery_tasks.py
- src/hct_mis_api/apps/payment/models/payment.py
- src/hct_mis_api/apps/payment/services/payment_gateway.py
- src/hct_mis_api/apps/payment/services/payment_plan_services.py
- src/hct_mis_api/one_time_scripts/update_pg_payment_plans_money_fields.py
- tests/unit/apps/payment/test_all_payment_plan_queries.py
- tests/unit/apps/payment/test_create_follow_up_payment_plan.py
- tests/unit/apps/payment/test_models.py
- tests/unit/apps/payment/test_payment_gateway_service.py
- tests/unit/apps/payment/test_payment_plan_services.py
[AB#253341](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/253341)
[AB#254863](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/254863)
> 254863_payment_plan_errors

- src/frontend/src/components/targeting/TargetingCriteriaDisplay/AddFilterTargetingCriteriaDisplay.tsx
- src/frontend/src/containers/forms/TargetingCriteriaForm.tsx
- src/hct_mis_api/apps/household/admin/individual.py
- src/hct_mis_api/apps/payment/services/payment_gateway.py
- src/hct_mis_api/apps/payment/services/payment_plan_services.py
- tests/unit/apps/payment/test_payment_plan_services.py
[AB#256413](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/256413)
> 🔥hotfix- fix_payment_gateway_payload_account_type

- src/hct_mis_api/apps/payment/filters.py
https://monitoring.hope.unicef.org/organizations/hope/issues/13372/?alert_rule_id=8&alert_timestamp=1749506703366&alert_type=email&environment=production&notification_uuid=1ed62bf7-f4dd-4709-8a1a-b6aa1aeee867&project=4&referrer=alert_email
https://monitoring.hope.unicef.org/organizations/hope/issues/13375/?environment=production&project=4&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
> fix_hide_targeting_payment_on_hh_payments_list

- src/hct_mis_api/apps/payment/views.py
[AB#256065](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/256065)
> 256065_payment_plan_summary_download_fix

- src/hct_mis_api/apps/payment/services/payment_plan_services.py
- src/hct_mis_api/apps/payment/xlsx/xlsx_payment_plan_export_per_fsp_service.py
- tests/unit/apps/payment/test_payment_plan_services.py
[AB#258835](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/258835)
> fix_export_payments_xlsx

- docker/entrypoint.sh
- manage.py
- src/hct_mis_api/apps/core/celery.py
- src/hct_mis_api/apps/grievance/celery_tasks.py
- src/hct_mis_api/apps/payment/celery_tasks.py
- src/hct_mis_api/apps/registration_datahub/celery_tasks.py
[AB#261137](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/261137): Remove queue from tasks[Enhancement 261137](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/261137): Remove queue from tasks
> Remove queue from tasks

- src/frontend/src/containers/tables/rdi/ImportedHouseholdsTable/ImportedHouseholdTable.tsx
- src/frontend/src/containers/tables/rdi/ImportedIndividualsTable/ImportedIndividualsTable.tsx
- src/hct_mis_api/apps/registration_datahub/tasks/rdi_merge.py
- tests/unit/apps/registration_datahub/test_rdi_merge.py
Fix rdi display when first RDI is already merged
Fix merge RDI when only collisions are inside RDI
> AB#261632 Fix extra RDI display and merge

- src/hct_mis_api/api/endpoints/rdi/mixin.py
- src/hct_mis_api/api/endpoints/rdi/push_people.py
- src/hct_mis_api/api/endpoints/rdi/upload.py
- tests/unit/api/test_push_people.py
add account creation to the pushpeople
> Handle document and account in push lax and push people endpoints

- src/hct_mis_api/apps/payment/services/payment_plan_services.py
- tests/unit/apps/payment/test_payment_plan_services.py
[AB#263381](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/263381)
> 263381_FSP_Details_is_dropped_when_PP_is_rejected_at_any_approval_stage

- src/hct_mis_api/apps/household/views.py
- tests/unit/apps/household/test_household_status_endpoint.py
[AB#225156](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/225156)
> 225156_Fix_too_broad_Exception_handling

- src/frontend/src/components/targeting/ResultsForPeople.tsx
[AB#266068](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/266068)
> Fix total num

- src/hct_mis_api/apps/payment/models/payment.py
- src/hct_mis_api/apps/payment/schema.py
- src/hct_mis_api/apps/payment/services/handle_total_cash_in_households.py
- src/hct_mis_api/apps/targeting/services/xlsx_export_targeting_service.py
- tests/unit/apps/payment/snapshots/snap_test_all_payment_plan_queries.py
- tests/unit/apps/payment/test_all_payment_plan_queries.py
[AB#258828](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/258828)
> 258828_Allow_creation_of_Payment_verification_for_pending_payments

- src/hct_mis_api/apps/payment/pdf/payment_plan_export_pdf_service.py
- src/hct_mis_api/apps/payment/templates/payment/payment_plan_summary_pdf_template.html
[AB#269568](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/269568): Payment Module - Payment plan summary file does not reflect accurately
> Payment plan summary file does not reflect accurately

- src/hct_mis_api/apps/payment/pdf/payment_plan_export_pdf_service.py
[AB#269568](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/269568): Payment Module - Payment plan summary file does not reflect accurately
> Payment Module - Payment plan summary file does not reflect accurately

- pyproject.toml
- src/frontend/package.json
- src/frontend/src/components/programs/CreateProgram/ProgramFieldSeriesStep.tsx
- src/frontend/src/components/programs/EditProgram/ProgramFieldSeriesStep.tsx
[AB#273090](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/273090)
> increase number of rounds for pdu fields

- src/hope/apps/core/api/views.py
Inherit from "PermissionsMixin" class as well
> Alter "BusinessAreaViewSet" class

- src/hope/apps/core/api/views.py
- tests/unit/api/test_business_area.py
> Alter mixin ordering for "BusinessAreaViewSet" class

- src/hope/apps/program/api/views.py
Extend from "PermissionsMixin" class as well
> Alter "BeneficiaryGroupViewSet" class

- src/hct_mis_api/apps/registration_datahub/apis/deduplication_engine.py
- src/hct_mis_api/apps/registration_datahub/services/biometric_deduplication.py
- tests/unit/apps/registration_datahub/test_biometric_deduplication_service.py
[AB#225212](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/225212)
> 225212 rdi adjust the finished status to show as finished with errors to indicate that dedup set has failed

- src/hope/apps/household/api/serializers/individual.py
[AB#276924](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/276924)
> REST - add field to Individual serializer - fix the Possible Duplicate flag always true

- src/frontend/src/components/paymentmodule/PaymentPlanDetails/AcceptanceProcess/AcceptanceProcess.tsx
- src/frontend/src/components/paymentmodule/PaymentPlanDetails/AcceptanceProcess/AcceptanceProcessRow.tsx
- src/frontend/src/components/paymentmodule/PaymentPlanDetails/AcceptanceProcess/GreyInfoCard.tsx
- src/frontend/src/components/paymentmodule/PaymentPlanDetails/AcceptanceProcess/MessageDialog.tsx
- src/frontend/src/components/paymentmodule/PaymentPlanDetails/PaymentPlanDetailsHeader/MarkAsReleasedPaymentPlan.tsx
- src/frontend/src/components/paymentmodulepeople/PaymentPlanDetails/AcceptanceProcess/AcceptanceProcessRow.tsx
- src/frontend/src/components/paymentmodulepeople/PaymentPlanDetails/AcceptanceProcess/GreyInfoCard.tsx
- src/frontend/src/components/paymentmodulepeople/PaymentPlanDetails/AcceptanceProcess/MessageDialog.tsx
[AB#278507](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/278507)
> [AB#278507]-fix display acceptance process row

- src/hct_mis_api/apps/payment/celery_tasks.py
[AB#278813](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/278813)
> 278813_Payment_plan_stuck_in_rule_engine_run_status
