backend/hct_mis_api/apps/registration_datahub/celery_tasks.py
backend/hct_mis_api/apps/utils/celery_utils.py

[AB#190670](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/190670)

[190670] LockNotOwnedError   hct_mis_api.apps.registration_datahub.celery_tasks.check_rdi_import_periodic_task

---

backend/hct_mis_api/apps/utils/admin.py
backend/hct_mis_api/apps/utils/tests/test_payment_plan_celery_tasks_mixin.py

[FIX] Fix celery button name

---

backend/hct_mis_api/apps/account/models.py
backend/hct_mis_api/apps/account/permissions.py
backend/hct_mis_api/apps/account/tests/test_check_permissions.py
backend/hct_mis_api/apps/account/tests/test_user_filters.py
backend/hct_mis_api/apps/grievance/schema.py
backend/hct_mis_api/apps/grievance/tests/test_cross_area_filter_available.py
backend/hct_mis_api/apps/grievance/tests/test_filter_grievance_by_cross_area.py
backend/hct_mis_api/apps/household/tests/test_household_area_query.py

[AB#192988](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/192988)

[192988] Fix permissions

---

backend/hct_mis_api/apps/core/tests/test_utils.py
backend/hct_mis_api/apps/core/utils.py

[AB#195063](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/195063): Sentry: ZeroDivisionError

Sentry Fix division by zero

---

frontend/src/components/programs/CreateProgram/programValidationSchema.ts
frontend/src/containers/forms/ProgramForm.tsx
frontend/src/containers/pages/program/CreateProgramPage.tsx
frontend/src/containers/pages/program/DuplicateProgramPage.tsx
frontend/src/containers/pages/program/EditProgramPage.tsx

[AB#196847](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/196847)

[196847] No validate end date for existing programmes

---

backend/hct_mis_api/apps/registration_datahub/validators.py

[AB#201171](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/201171): RDI - Cannot upload a file of people records that does not contain 'Households'/ 'Individuals' sheet
[AB#197912](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/197912): RDI - Cannot upload excel of people with no clear error

Fix RDI only People sheet validation

---

backend/hct_mis_api/apps/core/tests/test_utils.py
backend/hct_mis_api/apps/core/utils.py
backend/hct_mis_api/apps/household/admin/document.py
backend/hct_mis_api/apps/targeting/admin.py
backend/hct_mis_api/apps/targeting/tests/test_admin.py

[AB#196493](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/196493): TargetPopulation.DoesNotExist

Fix AutoCompleteFilter.choices for SoftDeletableModel

---

backend/hct_mis_api/apps/registration_datahub/tasks/rdi_kobo_create.py

[AB#200869](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/200869)
Temporary solution - user can upload only a file for now. In future will change to attachments and the fields on documents will be required

[200869] KOBO - issuing country and document number are not required

---

backend/hct_mis_api/apps/core/tests/test_utils.py
backend/hct_mis_api/apps/payment/models.py
backend/hct_mis_api/apps/payment/services/payment_gateway.py
backend/hct_mis_api/apps/payment/tests/test_payment_gateway_service.py
backend/hct_mis_api/apps/payment/utils.py
frontend/src/containers/tables/paymentmodule/PaymentsTable/PaymentsTableRow.tsx

[AB#199072](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/199072)

1199072_Add_Payment_Status_and_move_mapping_from_PG_to_HOPE_fix

---

src/hct_mis_api/apps/payment/admin.py
src/hct_mis_api/apps/payment/models.py
tests/unit/apps/grievance/test_model_validation.py
tests/unit/apps/payment/test_models1.py

https://monitoring.hope.unicef.org/organizations/hope/issues/5920/?referrer=alert_email&alert_type=email&alert_timestamp=1725391744476&alert_rule_id=7&notification_uuid=80213b17-5a0b-4f9e-879b-1968b006342d&environment=training

hotfix_add_financial_payment_provider_inline_validation

---

backend/hct_mis_api/apps/registration_datahub/tasks/deduplicate.py
backend/hct_mis_api/apps/registration_datahub/tests/test_handling_documents_duplicates.py

[AB#216567](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/216567)
Need to run
backend/hct_mis_api/apps/registration_datahub/celery_tasks.py
deduplicate_documents()
after merge to fix staging/prod existing RDIs
https://monitoring.hope.unicef.org/organizations/hope/issues/5737/events/6b9cd0f4b154403bacf4c3854ee1080d/
https://monitoring.hope.unicef.org/organizations/hope/issues/5737/events/51f25b6024fb4ab287a11c9f3da93dc8/?project=4

[hotfix] 216567 deduplication key error when deduplicating records

---

tests/selenium/programme_population/test_periodic_data_templates.py

This pull request includes a small but important change to the `test_periodic_data_template_create_and_download` method in the `tests/selenium/programme_population/test_periodic_data_templates.py` file. The change updates the directory path used for checking the existence of the downloaded file.
* [`tests/selenium/programme_population/test_periodic_data_templates.py`](diffhunk://#diff-b3cece820e14cf1ea4149a4492cfbd96fbba7283e5a264a6ccf86c271bcc2821L295-R297): Modified the `test_periodic_data_template_create_and_download` method to use `settings.DOWNLOAD_DIRECTORY` instead of the user's home directory for checking the downloaded file path.

Fixed test download path

---

.github/workflows/ci.yml
src/hct_mis_api/apps/program/utils.py
src/hct_mis_api/apps/registration_datahub/tasks/deduplicate.py
tests/unit/apps/registration_datahub/test_handling_documents_duplicates.py
tests/unit/apps/registration_datahub/test_program_population_to_pending_objects.py

* [hotfix] 216567 deduplication key error when deduplicating records (#4271)
* 2216567_Deduplication_Key_Error_when_deduplicating_records
* black
* remove distinct
* fix dedup logic, add ut
* lint
---------
* skip trivy failure
* fix document status when copy population (#4291)
---------

[Back merge] stg>dev (#4294)

---

src/hct_mis_api/apps/payment/api/views.py

[AB#217941](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/217941): Payment Module - Not saving user at 'created by' when uploading supporting document

Fixes // Payment Module - Supporting document

---

pyproject.toml
src/frontend/package.json
src/hct_mis_api/apps/periodic_data_update/api/views.py
tests/unit/apps/periodic_data_update/test_periodic_data_field_views.py

[AB#219855](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/219855)
This pull request includes updates to version numbers and changes to permission handling in the `PeriodicFieldViewSet`. The most important changes include updating the project version in multiple files and modifying the permission classes to use `IsAuthenticated`.
Version updates:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L144-R144): Updated project version from `2.12.0` to `2.12.1`.
* [`src/frontend/package.json`](diffhunk://#diff-12ee508ecc1901fe1a1d71ed459dba8454f3160983ee18b2c51b76ade45235d3L3-R3): Updated frontend version from `2.12.0` to `2.12.1`.
Permission handling:
* …

Individual page not accessible by Sudan CO

---

src/hct_mis_api/apps/household/models.py

[AB#219853](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/219853)
This pull request includes a small change to the `get_hash_key` method in the `household` model. The change adds an additional field to the list of attributes used to generate the hash key.
* [`src/hct_mis_api/apps/household/models.py`](diffhunk://#diff-a963e15e1fccdd2cfc730654e4f56ef448cbc13e9b68a2e222635e076118682cR1096): Added the `full_name` attribute to the list of fields in the `get_hash_key` method.

Fix detecting duplicated individual without names

---

src/hct_mis_api/api/filters.py
tests/unit/api/test_lookups.py

[AB#221081](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/221081)

[221081] Geo API - add filters

---

pyproject.toml
src/frontend/package.json
src/hct_mis_api/apps/household/celery_tasks.py

This pull request includes changes to update the version numbers in the project files and to improve the enrollment task in the `celery_tasks.py` file. The most important changes include version updates in `pyproject.toml` and `package.json`, and modifications to the `enroll_households_to_program_task` function to ensure proper indexing.
Version updates:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L140-R140): Updated the project version from `2.14.0` to `2.14.1`.
* [`src/frontend/package.json`](diffhunk://#diff-12ee508ecc1901fe1a1d71ed459dba8454f3160983ee18b2c51b76ade45235d3L3-R3): Updated the frontend version from `2.14.0` to `2.14.1`.
Function improvements:
* [`src/hct_mis_api/apps/household/celery_tasks.py`](diffhunk://#diff-9703 …

long running enrolment fix

---

development_tools/local_selenium_init.sh
src/hct_mis_api/apps/targeting/models.py
tests/selenium/conftest.py
tests/unit/apps/targeting/snapshots/snap_test_copy_target_population_mutation.py
tests/unit/apps/targeting/snapshots/snap_test_create_target_population_mutation.py
tests/unit/apps/targeting/test_copy_target_population_mutation.py
tests/unit/apps/targeting/test_create_target_population_mutation.py
tests/unit/apps/targeting/test_individual_block_filters.py
tests/unit/apps/targeting/test_targeting_criteria_rule_filter.py

Filter by collector's fields:
**if answer _YES_ > Delivery mechanism data (Wallet) must be VALID and have FIELD in the data json
if answer _NO_ > exclude all collectors with valid Delivery mechanism data (Wallet) that has the field**
Example: 
`api/unicorn/payment/deliverymechanismdata`

TP fix filtering if answer is NO

---

src/frontend/src/components/grievances/LookUps/LookUpReassignRole/LookUpReassignRole.tsx
src/frontend/src/components/grievances/ReassignMultipleRoleBox.tsx

This pull request includes several changes to improve the robustness of the `LookUpReassignRole` and `ReassignMultipleRoleBox` components by adding optional chaining to handle potential undefined values. The most important changes are:
Enhancements to handle potential undefined values:
* [`src/frontend/src/components/grievances/LookUps/LookUpReassignRole/LookUpReassignRole.tsx`](diffhunk://#diff-b6665d25421d133a941cf8c1ccc66caec107660f7f558cb43552f8d9c583dacdL122-R122): Updated `initialValues` to use optional chaining for `individualData.individual` to prevent errors when `individualData` is undefined.
* [`src/frontend/src/components/grievances/ReassignMultipleRoleBox.tsx`](diffhunk://#diff-fb7edac7b51bcbc78db5bdc5b8d765cf7bc8d3a6a429e3be17c46af1a887c27cL100-R99): Added optional chaining …

AB#226656 Error Cannot read properties of undefined Grievance ticket

---

src/frontend/src/containers/tables/rdi/ImportedHouseholdsTable/ImportedHouseholdTableRow.tsx
src/frontend/src/containers/tables/rdi/ImportedIndividualsTable/ImportedIndividualsTableRow.tsx
src/hct_mis_api/apps/account/permissions.py
src/hct_mis_api/apps/household/schema.py
src/hct_mis_api/apps/utils/models.py

This pull request includes several changes aimed at improving the handling of merge status objects in the `household` schema and permissions. The most important changes include modifications to the `get_node` method, updates to various resolve methods to use `all_merge_status_objects`, and adjustments to the `SoftDeletableRepresentationMergeStatusModel`.
* [`src/hct_mis_api/apps/account/permissions.py`](diffhunk://#diff-526f5cc032a7ec5d81b4342d2d3eb2fda6679d8c61c8c7dcead12956814c0362L381-R386): Updated the `get_node` method to accept additional keyword arguments and use `get_object_queryset` if provided.
* [`src/hct_mis_api/apps/household/schema.py`](diffhunk://#diff-7e14e32a1e8c53a8b829295bd9f9ca07a017b67fd263ffab4737d33062d21ba7R268-R278): Added the `get_node` method to the …

Fixes to managers for mergable models

---

src/hct_mis_api/apps/grievance/services/data_change/utils.py
tests/unit/apps/grievance/test_services_utils.py

[AB#229457](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/229457): Flexible field of date type cannot be updated through Grievance ticket

Fix Grievance validate flex fields value with date type

---

src/hct_mis_api/apps/grievance/services/data_change/utils.py
tests/unit/apps/grievance/test_services_utils.py

[AB#230447](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/230447): Madagascar: Cannot close estimated birth date change grievance ticket

STG Fix grievance upd ind

---

src/hct_mis_api/apps/payment/models/payment.py
src/hct_mis_api/apps/payment/schema.py
tests/unit/apps/payment/snapshots/snap_test_all_payment_plan_queries.py

[AB#236467](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/236467): Enable 'Auth codes' file export when records are at 'Transferred to FSP' and keep the file enabled until exported once

Upd Export PaymentPlan XLSX with auth code

---

pyproject.toml
src/frontend/package.json
tests/selenium/page_object/targeting/targeting_details.py
tests/selenium/targeting/test_targeting.py

[AB#237264](https://dev.azure.com/unicef/ICTD-HCT-MIS/_workitems/edit/237264): Fix very unstable E2E test TestCreateTargeting.test_create_targeting_with_pdu_null_criteria

Fix e2e Create TP

---

src/hct_mis_api/apps/payment/services/payment_gateway.py
tests/unit/apps/payment/test_payment_gateway_service.py

[AB#238963](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/238963): Payment Verification - Cannot create Payment verification plan

STG // Fix create PaymentVerificationSummary after PG sync

---

src/hct_mis_api/apps/core/api/mixins.py
src/hct_mis_api/apps/geo/api/views.py
tests/unit/api/test_area.py
tests/unit/api/test_business_area.py

[AB#245537](https://unicef.visualstudio.com/4e044e8d-bc28-4768-8074-f80ff6e4a0e5/_workitems/edit/245537)

[245537] Handle permission check on REST endpoints based on a token presence (internal and external endpoints in one viewset)

---

.github/helpers/.env-unit
.github/helpers/docker-compose.tst.yml
development_tools/.env.example
development_tools/compose.yml
docker/Dockerfile
docker/entrypoint.sh
src/hct_mis_api/config/env.py
src/hct_mis_api/config/settings.py

This pull request removes support for SSL mode in PostgreSQL configurations and simplifies related setup processes. Additionally, it adjusts database health check intervals and removes unused dependencies and scripts.
* Removed the `POSTGRES_SSL_MODE` environment variable from various configuration files, including `.github/helpers/.env-unit`, `.github/helpers/docker-compose.tst.yml`, and `development_tools/.env.example`. [[1]](diffhunk://#diff-bd16a15d2ec42e95e59d63607376c7f8267082daf6e69b81be0d1611d1ca42daL8) [[2]](diffhunk://#diff-4dfb63e2ea8355ecace6be3bfe6bc23250f483e8f78cb0f11d1ecec782597244L25) [[3]](diffhunk://#diff-c1e4eb25bd12f9eac7dfd5256e255ed48aa90f92dadc950394bdf4aa60285edeL14)
* Deleted SSL-related settings in `src/hct_mis_api/config/env.py` and …

not using cert on postgres

---

pyproject.toml
src/frontend/package.json
src/hct_mis_api/apps/payment/admin.py
tests/unit/apps/grievance/test_model_validation.py

This pull request includes a small change to the `clean` method in `src/hct_mis_api/apps/payment/admin.py`. The change ensures compatibility with handling multiple delivery mechanisms by using `getlist` instead of `get` when accessing `self.data`.

AB#254781 Fix validation on xlsx template delivery mechanisms

---

docker/Dockerfile
pyproject.toml
src/frontend/package.json
src/hct_mis_api/apps/payment/managers.py
src/hct_mis_api/apps/payment/models/payment.py
tests/unit/apps/payment/test_models.py
uv.lock

add legacy-cgi
FYI
The cgi module was officially removed in Python 3.13 as part of PEP 594, which deprecated and removed older, outdated modules from the standard library.

Back merge Staging > dev

---

src/hct_mis_api/apps/targeting/services/targeting_service.py
tests/unit/apps/payment/test_payment_plan_services.py
tests/unit/apps/targeting/test_individual_block_filters.py
uv.lock

[AB#271185](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/271185): Haiti: Excluded Target Population Entries still appear in Target Population

Fix Excluded Target Population Entries still appear in Target Population

---

src/hope/apps/payment/api/views.py
tests/unit/apps/payment/test_payment_plan_views.py

[AB#277893](https://unicef.visualstudio.com/ICTD-HCT-MIS/_workitems/edit/277893): Payment Module - PP Status does not change to formula engine run, but remains at Locked when applying EF on Payment records

Fix Payment Module - PP Status does not change to formula engine run
